### PR TITLE
Added verbosity of exceptions during minification

### PR DESCRIPTION
**Pull request by brad-lucas**
Converted the Trace.TraceWarning call to a top-level message that something wrong happened and added Trace.TraceInformational calls for added verbosity in debugging issues.

### CODE REVIEW

**Comment by benmccallum** [comment]
Awesome, I'm away from a real machine at the moment to finish this off but should be able to in an hour or so. 

FYI, This looks cool and like it would've helped you in terms of being able to set breakpoints in the source of my package. Core RC1+ though, and I don't have any need to upgrade at this stage :p
https://github.com/dotnet/sourcelink/blob/master/README.md

**Comment by benmccallum** [comment]
Released as v2.2.0 on NuGet. Thanks again for the contribution!

**Comment by brad-lucas** [comment]
Awesome, thanks so much for the quick turnaround, Ben, and thanks again for the great package!

I'm, generally, the opposite of a frequent contributor, but let me know if there's anything I could potentially help with if you've got a backlog. :)

**Comment by benmccallum** [comment]
Nah nothing on this package, it's mostly for supporting those legacy projects where people can't get onto task runners for builds (grunt/gulp) or these days webpack

**Pull request merged**
