### PR TITLE
Update ajax min

### PR DESCRIPTION
**Pull request by LodewijkSioen**
You'll need to merge #5 first. Updates AjaxMin to a more recent version than the one used internally in WebGrease.
- Eliminate the //@ -> //# replacement hack
- Makes the scriptmaps Chrome compatible

### CODE REVIEW

**Comment by benmccallum** [comment]
Hey @LodewijkSioen,

Sorry for the delay, but I've merged the two PRs now.

Currently testing them and it seems like generating the minified file contents takes ages! Any idea what this might be? Can't release an updated NuGet package until I've figured this out.

Cheers,
Ben

**Comment by benmccallum** [comment]
It's definitely the following line, taking very very long:
`string contentMinified = minifier.MinifyJavaScript(contentConcatedString, settings);`

**Comment by LodewijkSioen** [comment]
This only happens when debugging :-1: It seems to be [a bug](https://ajaxmin.codeplex.com/workitem/21834) in the current version of AjaxMin, but that project seems to be quite dead.

What you can do is wrap [this line](https://github.com/benmccallum/AspNetBundling/blob/master/AspNetBundling/ScriptWithSourceMapBundleBuilder.cs#L127) like this:

    if (!Diagnostics.Debugger.IsAttached)
    {
        contentConcated.AppendLine("///#source 1 1 " + file.VirtualFile.VirtualPath);
    }

But then you'll loose the sourcemaps on the concated files.

**Comment by benmccallum** [comment]
@madskristensen, are you also just dealing with this in Web Essentials?

**Comment by benmccallum** [comment]
I wonder if there is a version of AjaxMin we can go to that doesn't have this problem but satisfies Chrome's dev tools for sourcemapping?

**Comment by benmccallum** [comment]
Hey @LodewijkSioen,
I've added that line as you suggested, and also some debugging comments in the bundled file contents and map files to make it obvious to everyone that bundling won't work in the scenario where Debugger.IsAttached. Also updated the readme to mark it as a known issues, pending AjaxMin fix, which it looks like Mads has already logged with the author too so hopefully it gets fixed eventually. Cheers, and thanks for the contribs again!

**Comment by LodewijkSioen** [comment]
I wouldn't expect anything from AjaxMin. That project seems very quiet now. It seems like everybody is moving away from server-side bundling to build-time bundling with grunt/gulp. That said, I enjoyed making these controbutions.

**Pull request merged**
