### PR TITLE
SourceMaps as Bundles

### PR DESCRIPTION
**Pull request by LodewijkSioen**
If you want this:
~~Instead of writing the sourcemap to the filesystem, embed it as a base64 encoded string in the bundle. I can't find much documentation that describes this feature, but it works in Firefox and IE (somehow Chrome doesn't work)~~

Change of plans: it's the sourcemap now lives in a bundle of its own.

### CODE REVIEW

**Comment by benmccallum** [comment]
Hey, thanks for the contrib. I'm confused though, wouldn't base64 encoding the sourceMap into the end of the minified file defeat the purpose of minifying? The file would effectively become a combination of raw and minified. It'd be huge.

**Comment by benmccallum** [comment]
I was just thinking of doing what the bundles do for hosting and just make "virtual" urls for the .map files that magically resolve with a handler/module.

**Comment by LodewijkSioen** [comment]
On the size: that would be true if the sourcemap contained the content of all the files, but a sourcemap only contains references to the original files. They are only a fraction of the size. Honestly, I have no idea how they do it, it's magic.

On using a bundle for the sourcemap: this also crossed my mind, but I thought you couldn't add a Bundle from inside a Bundle. But now I've noticed that BundleCollection is a property on BundleContext. So in theory this should be possible (and probably a nicer solution than this one).

**Comment by LodewijkSioen** [comment]
So yesterday I spiked the putting the Sourcemap in a seperate bundle and it seems to work :smile:

**Comment by benmccallum** [comment]
Haha awesome. I'm really busy at the moment but I'll look at it this weekend and see if we can get it merged and released! Cheers.

**Comment by LodewijkSioen** [comment]
Okay. I'll test it some more and clean it up a little by then.

**Comment by LodewijkSioen** [comment]
I think I'm done with it. There is also pull request #6, which updates AjaxMin and eliminates the hack that replaced //@ with //#. It also makes the sourcemaps Chrome compatible.

**Comment by benmccallum** [comment]
Hey @LodewijkSioen, it didn't look like the Map AdHocBundle objects were being added to the BundleCollection so I added that. Also, I changed their virtual path for hosting to not be .map, but just bundleName + "map", like jquerymap to avoid IIS picking it up as a static file and handling it, rather than it being served by AspNetOptimization's bundle module.

**Comment by benmccallum** [comment]
It's up on NuGet as 2.0.1 if you wanna start using in projects. :)

**Comment by LodewijkSioen** [comment]
Super, I'll check it out shortly.

**Comment by gaui** [comment]
Shouldn't you be able to hover over variables in the Chrome debugger and see their values? I can only "watch" minified variable names. Is it just me or is this how sourcemaps work? I thought it would be like debugging un-minified code.

**Comment by benmccallum** [comment]
Hey @gaui, 

Ideally yes but I'm not 100% sure. I'll try on a different site I have which uses grunt and uglify to do source mapping. I'll also try using web essentials to do the same bundle and do a file diff between both. 

Not being able to inspect but only watch screams out to me that the mapping is off by a line or so (if that's even possible). 

The AspNet Optimzation library has been deprecated in favour of grunt/gulp these days. And AjaxMin doesn't get much love. So unless my code is doing something wrong I'm not sure how to help. 

Cheers,
Ben

**Comment by gaui** [comment]
The breakpoints are hit, but hovering over variables gives nothing. But under Locals the minified variables are displayed, so I can insert a watch on them. But I thought you should be able to hover over the variable names and get their values.

**Pull request merged**
